services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
      MYSQL_DATABASE: db_integrador_tp1
      MYSQL_USER: app_user
      MYSQL_PASSWORD: "12345"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
